// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1310:Field names should not contain underscore", Justification = "Represents a Kafka Topic which contains underscores in its naming convention.", Scope = "member", Target = "~F:Assurity.Kafka.Utilities.Constants.Topics.PPOLC_EVENT")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1310:Field names should not contain underscore", Justification = "Represents a Kafka Topic which contains underscores in its naming convention.", Scope = "member", Target = "~F:Assurity.Kafka.Utilities.Constants.Topics.PPOLM_POLICY_BENEFIT_MISC_EVENT")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1310:Field names should not contain underscore", Justification = "Represents a Kafka Topic which contains underscores in its naming convention.", Scope = "member", Target = "~F:Assurity.Kafka.Utilities.Constants.Topics.PNAME_EVENT")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1310:Field names should not contain underscore", Justification = "Represents a Kafka Topic which contains underscores in its naming convention.", Scope = "member", Target = "~F:Assurity.Kafka.Utilities.Constants.Topics.PADDR_EVENT")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1310:Field names should not contain underscore", Justification = "Represents a Kafka Topic which contains underscores in its naming convention.", Scope = "member", Target = "~F:Assurity.Kafka.Utilities.Constants.Topics.PPEND_NEW_BUSINESS_PENDING_EVENT")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1310:Field names should not contain underscore", Justification = "Represents a Kafka Topic which contains underscores in its naming convention.", Scope = "member", Target = "~F:Assurity.Kafka.Utilities.Constants.Topics.PPEND_NEW_BUS_PEND_UNDERWRITING_EVENT")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1310:Field names should not contain underscore", Justification = "Represents a Kafka Topic which contains underscores in its naming convention.", Scope = "member", Target = "~F:Assurity.Kafka.Utilities.Constants.Topics.PRELA_RELATIONSHIP_MASTER_EVENT")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1310:Field names should not contain underscore", Justification = "Represents a Kafka Topic which contains underscores in its naming convention.", Scope = "member", Target = "~F:Assurity.Kafka.Utilities.Constants.Topics.PCOMC_COMMISSION_CONTROL_TYPE_S_EVENT")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1310:Field names should not contain underscore", Justification = "Represents a Kafka Topic which contains underscores in its naming convention.", Scope = "member", Target = "~F:Assurity.Kafka.Utilities.Constants.Topics.PCOMC_COMMISSION_CONTROL_EVENT")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1310:Field names should not contain underscore", Justification = "Represents a Kafka Topic which contains underscores in its naming convention.", Scope = "member", Target = "~F:Assurity.Kafka.Utilities.Constants.Topics.PHIER_AGENT_HIERARCHY_EVENT")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1310:Field names should not contain underscore", Justification = "Represents a Kafka Topic which contains underscores in its naming convention.", Scope = "member", Target = "~F:Assurity.Kafka.Utilities.Constants.Topics.PMUIN_MULTIPLE_INSUREDS_EVENT")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1310:Field names should not contain underscore", Justification = "Represents a Kafka Topic which contains underscores in its naming convention.", Scope = "member", Target = "~F:Assurity.Kafka.Utilities.Constants.Topics.PNALK_EVENT")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1310:Field names should not contain underscore", Justification = "Represents a Kafka Topic which contains underscores in its naming convention.", Scope = "member", Target = "~F:Assurity.Kafka.Utilities.Constants.Topics.PPBEN_POLICY_BENEFITS_EVENT")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1310:Field names should not contain underscore", Justification = "Represents a Kafka Topic which contains underscores in its naming convention.", Scope = "member", Target = "~F:Assurity.Kafka.Utilities.Constants.Topics.PPBEN_POLICY_BENEFITS_TYPES_BA_OR_EVENT")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1310:Field names should not contain underscore", Justification = "Represents a Kafka Topic which contains underscores in its naming convention.", Scope = "member", Target = "~F:Assurity.Kafka.Utilities.Constants.Topics.PPBEN_POLICY_BENEFITS_TYPES_BF_EVENT")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1310:Field names should not contain underscore", Justification = "Represents a Kafka Topic which contains underscores in its naming convention.", Scope = "member", Target = "~F:Assurity.Kafka.Utilities.Constants.Topics.PPBEN_POLICY_BENEFITS_TYPES_SL_EVENT")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1310:Field names should not contain underscore", Justification = "Represents a Kafka Topic which contains underscores in its naming convention.", Scope = "member", Target = "~F:Assurity.Kafka.Utilities.Constants.Topics.PPBEN_POLICY_BENEFITS_TYPES_SP_EVENT")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1310:Field names should not contain underscore", Justification = "Represents a Kafka Topic which contains underscores in its naming convention.", Scope = "member", Target = "~F:Assurity.Kafka.Utilities.Constants.Topics.PPBEN_POLICY_BENEFITS_TYPES_SU_EVENT")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1310:Field names should not contain underscore", Justification = "Represents a Kafka Topic which contains underscores in its naming convention.", Scope = "member", Target = "~F:Assurity.Kafka.Utilities.Constants.Topics.ProductDescription_EVENT")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1310:Field names should not contain underscore", Justification = "Represents a Kafka Topic which contains underscores in its naming convention.", Scope = "member", Target = "~F:Assurity.Kafka.Utilities.Constants.Topics.PMEDR_EVENT")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1310:Field names should not contain underscore", Justification = "Represents a Kafka Topic which contains underscores in its naming convention.", Scope = "member", Target = "~F:Assurity.Kafka.Utilities.Constants.Topics.PRQRM_EVENT")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1310:Field names should not contain underscore", Justification = "Represents a Kafka Topic which contains underscores in its naming convention.", Scope = "member", Target = "~F:Assurity.Kafka.Utilities.Constants.Topics.PRQRMTBL_EVENT")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1310:Field names should not contain underscore", Justification = "Represents a Kafka Topic which contains underscores in its naming convention.", Scope = "member", Target = "~F:Assurity.Kafka.Utilities.Constants.Topics.SysNBRequirements_EVENT")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1310:Field names should not contain underscore", Justification = "Represents a Kafka Topic which contains underscores in its naming convention.", Scope = "member", Target = "~F:Assurity.Kafka.Utilities.Constants.Topics.SysACAgentData_EVENT")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1310:Field names should not contain underscore", Justification = "Represents a Kafka Topic which contains underscores in its naming convention.", Scope = "member", Target = "~F:Assurity.Kafka.Utilities.Constants.Topics.SysACAgentMarketCodes_EVENT")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1310:Field names should not contain underscore", Justification = "Represents a Kafka Topic which contains underscores in its naming convention.", Scope = "member", Target = "~F:Assurity.Kafka.Utilities.Constants.Topics.SysZ9Process_EVENT")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1310:Field names should not contain underscore", Justification = "Represents a Kafka Topic which contains underscores in its naming convention.", Scope = "member", Target = "~F:Assurity.Kafka.Utilities.Constants.Topics.QUEUES_EVENT")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1310:Field names should not contain underscore", Justification = "Represents a Kafka Topic which contains underscores in its naming convention.", Scope = "member", Target = "~F:Assurity.Kafka.Utilities.Constants.Topics.PACTG_EVENT")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1310:Field names should not contain underscore", Justification = "Represents a Kafka Topic which contains underscores in its naming convention.", Scope = "member", Target = "~F:Assurity.Kafka.Utilities.Constants.Topics.PBDRV_EVENT")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1310:Field names should not contain underscore", Justification = "Represents a Kafka Topic which contains underscores in its naming convention.", Scope = "member", Target = "~F:Assurity.Kafka.Utilities.Constants.Topics.PGRUP_GROUP_MASTER_EVENT")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1310:Field names should not contain underscore", Justification = "Represents a Kafka Topic which contains underscores in its naming convention.", Scope = "member", Target = "~F:Assurity.Kafka.Utilities.Constants.Topics.PACON_ANNUITY_POLICY_EVENT")]